# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('phone', 'email')]),
        ),
    ]
